// src/utils/centerHelpers.ts

/**
 * Devuelve una lista de todas las columnas válidas para la tabla `CentersDescription`.
 * Esto centraliza la lista de campos del catastro, evitando que esté duplicada o
 * hardcodeada directamente en el controlador de actualización.
 */
export function getValidDescriptionColumns(): string[] {
    return [
        "nombre_organizacion", "nombre_dirigente", "cargo_dirigente", "telefono_contacto",
        "tipo_inmueble", "numero_habitaciones", "estado_conservacion", "muro_hormigon",
        "muro_albaneria", "muro_tabique", "muro_adobe", "muro_mat_precario", "piso_parquet",
        "piso_ceramico", "piso_alfombra", "piso_baldosa", "piso_radier", "piso_enchapado",
        "piso_tierra", "techo_tejas", "techo_losa", "techo_planchas", "techo_fonolita",
        "techo_mat_precario", "techo_sin_cubierta", "espacio_10_afectados", "diversidad_funcional",
        "areas_comunes_accesibles", "espacio_recreacion", "observaciones_espacios_comunes",
        "agua_potable", "agua_estanques", "electricidad", "calefaccion", "alcantarillado",
        "observaciones_servicios_basicos", "estado_banos", "wc_proporcion_personas",
        "banos_genero", "banos_grupos_prioritarios", "cierre_banos_emergencia",
        "lavamanos_proporcion_personas", "dispensadores_jabon", "dispensadores_alcohol_gel",
        "papeleros_banos", "papeleros_cocina", "duchas_proporcion_personas",
        "lavadoras_proporcion_personas", "observaciones_banos_y_servicios_higienicos",
        "posee_habitaciones", "separacion_familias", "sala_lactancia",
        "observaciones_distribucion_habitaciones", "cuenta_con_mesas_sillas",
        "cocina_comedor_adecuados", "cuenta_equipamiento_basico_cocina", "cuenta_con_refrigerador",
        "cuenta_set_extraccion", "observaciones_herramientas_mobiliario",
        "sistema_evacuacion_definido", "cuenta_con_senaleticas_adecuadas",
        "observaciones_condiciones_seguridad_proteccion_generales", "existe_lugar_animales_dentro",
        "existe_lugar_animales_fuera", "existe_jaula_mascota", "existe_recipientes_mascota",
        "existe_correa_bozal", "reconoce_personas_dentro_de_su_comunidad",
        "no_reconoce_personas_dentro_de_su_comunidad", "observaciones_dimension_animal",
        "existen_cascos", "existen_gorros_cabello", "existen_gafas", "existen_caretas",
        "existen_mascarillas", "existen_respiradores", "existen_mascaras_gas",
        "existen_guantes_latex", "existen_mangas_protectoras", "existen_calzados_seguridad",
        "existen_botas_impermeables", "existen_chalecos_reflectantes", "existen_overoles_trajes",
        "existen_camillas_catre", "existen_alarmas_incendios", "existen_hidrantes_mangueras",
        "existen_senaleticas", "existen_luces_emergencias", "existen_extintores", "existen_generadores",
        "existen_baterias_externas", "existen_altavoces", "existen_botones_alarmas",
        "existen_sistemas_monitoreo", "existen_radio_recargable", "existen_barandillas_escaleras",
        "existen_puertas_emergencia_rapida", "existen_rampas", "existen_ascensores_emergencia",
        "existen_botiquines", "existen_camilla_emergencia", "existen_sillas_ruedas", "existen_muletas",
        "existen_desfibriladores", "existen_senales_advertencia", "existen_senales_informativas",
        "existen_senales_exclusivas", "observaciones_seguridad_comunitaria", "importa_elementos_seguridad",
        "observaciones_importa_elementos_seguridad", "importa_conocimientos_capacitaciones",
        "observaciones_importa_conocimientos_capacitaciones"
    ];
}

/**
 * Mapea los datos del cuerpo de la petición (request body) a los nombres de las columnas
 * de la tabla `CentersDescription` en la base de datos.
 * @param centerId El ID del centro al que se asociarán los datos.
 * @param requestBody El objeto `req.body` o los datos restantes de él.
 * @returns Un objeto listo para ser insertado en la base de datos.
 */
export function mapCatastroDataFromRequest(centerId: string, requestBody: any): { [key: string]: any } {
    return {
        center_id: centerId,
        nombre_organizacion: requestBody.name || null,  // El frontend envía 'name', no 'organizationName'
        nombre_dirigente: requestBody.nombre_dirigente || null,  // Usar el campo correcto del frontend
        cargo_dirigente: requestBody.cargo_dirigente || null,  // Usar el campo correcto del frontend  
        telefono_contacto: requestBody.telefono_contacto || null,  // Usar el campo correcto del frontend
        tipo_inmueble: requestBody.tipo_inmueble || null,
        numero_habitaciones: requestBody.numero_habitaciones || null,
        estado_conservacion: requestBody.estado_conservacion || null,
        muro_hormigon: requestBody.muro_hormigon,
        muro_albaneria: requestBody.muro_albaneria,
        muro_tabique: requestBody.muro_tabique,
        muro_adobe: requestBody.muro_adobe,
        muro_mat_precario: requestBody.muro_mat_precario,
        piso_parquet: requestBody.piso_parquet,
        piso_ceramico: requestBody.piso_ceramico,
        piso_alfombra: requestBody.piso_alfombra,
        piso_baldosa: requestBody.piso_baldosa,
        piso_radier: requestBody.piso_radier,
        piso_enchapado: requestBody.piso_enchapado,
        piso_tierra: requestBody.piso_tierra,
        techo_tejas: requestBody.techo_tejas,
        techo_losa: requestBody.techo_losa,
        techo_planchas: requestBody.techo_planchas,
        techo_fonolita: requestBody.techo_fonolita,
        techo_mat_precario: requestBody.techo_mat_precario,
        techo_sin_cubierta: requestBody.techo_sin_cubierta,
        espacio_10_afectados: requestBody.espacio_10_afectados || null,
        diversidad_funcional: requestBody.diversidad_funcional || null,
        areas_comunes_accesibles: requestBody.areas_comunes_accesibles || null,
        espacio_recreacion: requestBody.espacio_recreacion || null,
        observaciones_espacios_comunes: requestBody.observaciones_espacios_comunes || null,
        agua_potable: requestBody.agua_potable || null,
        agua_estanques: requestBody.agua_estanques || null,
        electricidad: requestBody.electricidad || null,
        calefaccion: requestBody.calefaccion || null,
        alcantarillado: requestBody.alcantarillado || null,
        observaciones_servicios_basicos: requestBody.observaciones_servicios_basicos || null,
        estado_banos: requestBody.estado_banos || null,
        wc_proporcion_personas: requestBody.wc_proporcion_personas || null,
        banos_genero: requestBody.banos_genero || null,
        banos_grupos_prioritarios: requestBody.banos_grupos_prioritarios || null,
        cierre_banos_emergencia: requestBody.cierre_banos_emergencia || null,
        lavamanos_proporcion_personas: requestBody.lavamanos_proporcion_personas || null,
        dispensadores_jabon: requestBody.dispensadores_jabon,
        dispensadores_alcohol_gel: requestBody.dispensadores_alcohol_gel,
        papeleros_banos: requestBody.papeleros_banos,
        papeleros_cocina: requestBody.papeleros_cocina,
        duchas_proporcion_personas: requestBody.duchas_proporcion_personas || null,
        lavadoras_proporcion_personas: requestBody.lavadoras_proporcion_personas || null,
        observaciones_banos_y_servicios_higienicos: requestBody.observaciones_banos_y_servicios_higienicos || null,
        posee_habitaciones: requestBody.posee_habitaciones || null,
        separacion_familias: requestBody.separacion_familias || null,
        sala_lactancia: requestBody.sala_lactancia || null,
        observaciones_distribucion_habitaciones: requestBody.observaciones_distribucion_habitaciones || null,
        cuenta_con_mesas_sillas: requestBody.cuenta_con_mesas_sillas || null,
        cocina_comedor_adecuados: requestBody.cocina_comedor_adecuados || null,
        cuenta_equipamiento_basico_cocina: requestBody.cuenta_equipamiento_basico_cocina || null,
        cuenta_con_refrigerador: requestBody.cuenta_con_refrigerador || null,
        cuenta_set_extraccion: requestBody.cuenta_set_extraccion || null,
        observaciones_herramientas_mobiliario: requestBody.observaciones_herramientas_mobiliario || null,
        sistema_evacuacion_definido: requestBody.sistema_evacuacion_definido || null,
        cuenta_con_senaleticas_adecuadas: requestBody.cuenta_con_senaleticas_adecuadas || null,
        observaciones_condiciones_seguridad_proteccion_generales: requestBody.observaciones_condiciones_seguridad_proteccion_generales || null,
        existe_lugar_animales_dentro: requestBody.existe_lugar_animales_dentro || null,
        existe_lugar_animales_fuera: requestBody.existe_lugar_animales_fuera || null,
        existe_jaula_mascota: requestBody.existe_jaula_mascota,
        existe_recipientes_mascota: requestBody.existe_recipientes_mascota,
        existe_correa_bozal: requestBody.existe_correa_bozal,
        reconoce_personas_dentro_de_su_comunidad: requestBody.reconoce_personas_dentro_de_su_comunidad,
        no_reconoce_personas_dentro_de_su_comunidad: requestBody.no_reconoce_personas_dentro_de_su_comunidad,
        observaciones_dimension_animal: requestBody.observaciones_dimension_animal || null,
        existen_cascos: requestBody.existen_cascos,
        existen_gorros_cabello: requestBody.existen_gorros_cabello,
        existen_gafas: requestBody.existen_gafas,
        existen_caretas: requestBody.existen_caretas,
        existen_mascarillas: requestBody.existen_mascarillas,
        existen_respiradores: requestBody.existen_respiradores,
        existen_mascaras_gas: requestBody.existen_mascaras_gas,
        existen_guantes_latex: requestBody.existen_guantes_latex,
        existen_mangas_protectoras: requestBody.existen_mangas_protectoras,
        existen_calzados_seguridad: requestBody.existen_calzados_seguridad,
        existen_botas_impermeables: requestBody.existen_botas_impermeables,
        existen_chalecos_reflectantes: requestBody.existen_chalecos_reflectantes,
        existen_overoles_trajes: requestBody.existen_overoles_trajes,
        existen_camillas_catre: requestBody.existen_camillas_catre,
        existen_alarmas_incendios: requestBody.existen_alarmas_incendios,
        existen_hidrantes_mangueras: requestBody.existen_hidrantes_mangueras,
        existen_senaleticas: requestBody.existen_senaleticas,
        existen_luces_emergencias: requestBody.existen_luces_emergencias,
        existen_extintores: requestBody.existen_extintores,
        existen_generadores: requestBody.existen_generadores,
        existen_baterias_externas: requestBody.existen_baterias_externas,
        existen_altavoces: requestBody.existen_altavoces,
        existen_botones_alarmas: requestBody.existen_botones_alarmas,
        existen_sistemas_monitoreo: requestBody.existen_sistemas_monitoreo,
        existen_radio_recargable: requestBody.existen_radio_recargable,
        existen_barandillas_escaleras: requestBody.existen_barandillas_escaleras,
        existen_puertas_emergencia_rapida: requestBody.existen_puertas_emergencia_rapida,
        existen_rampas: requestBody.existen_rampas,
        existen_ascensores_emergencia: requestBody.existen_ascensores_emergencia,
        existen_botiquines: requestBody.existen_botiquines,
        existen_camilla_emergencia: requestBody.existen_camilla_emergencia,
        existen_sillas_ruedas: requestBody.existen_sillas_ruedas,
        existen_muletas: requestBody.existen_muletas,
        existen_desfibriladores: requestBody.existen_desfibriladores,
        existen_senales_advertencia: requestBody.existen_senales_advertencia,
        existen_senales_informativas: requestBody.existen_senales_informativas,
        existen_senales_exclusivas: requestBody.existen_senales_exclusivas,
        observaciones_seguridad_comunitaria: requestBody.observaciones_seguridad_comunitaria || null,
        importa_elementos_seguridad: requestBody.importa_elementos_seguridad,
        observaciones_importa_elementos_seguridad: requestBody.observaciones_importa_elementos_seguridad || null,
        importa_conocimientos_capacitaciones: requestBody.importa_conocimientos_capacitaciones,
        observaciones_importa_conocimientos_capacitaciones: requestBody.observaciones_importa_conocimientos_capacitaciones || null,
    };
}